### PR TITLE
Add Cornucopia & Guilds 2nd Edition.

### PR DESCRIPTION
**Pull request by dbgalur**

### CODE REVIEW

**Comment by dbgalur** [comment]
The 1st edition had a separate Guilds set and a separate Cornucopia set.  In the 2nd edition they are combined.
There were three options for what to do with the sets of the cards.
1: Leave the 1st edition cards as either 'Guilds' or 'Cornucopia' and label the new 2nd edition cards as 'Guilds & Cornucopia'.
2: Leave the 1st edition cards as either 'Guilds' or 'Cornucopia' and split the new 2nd edition cards between 'Guilds' and 'Cornucopia' as appropriate.
3: Change the set of the 1st edition cards to 'Guilds & Cornucopia' and label the new 2nd edition cards as 'Guilds & Cornucopia'.
I opted for 2 after waffling a bit on the decision, but if you feel strongly, I can go with one of the others.

**Comment by TruthNZ** [comment]
Hey, awesome work - I've been so busy with life I haven't had the spare time to do all the 2nd ed updates (the joys of solo parenting).

I'd recommend we stick with the separate sets of Guilds and Cornucopia for 1st ed, since there's a fair chance of someone having purchased only one of the those sets. And then have the 2nd ed cards as the combined set, since that's how they'd be purchased.
If you've got the time, would you be able to redo these changes with that in mind?

**Comment by dbgalur** [comment]
Can you elaborate a bit more what you mean? I didn't quite understand.  The
current implementation leaves the first edition cards as is, and breaks the
second edition cards into their component sets.

**Comment by TruthNZ** [comment]
The intent of the sets is for people to be able to select which ones they own, so the app only draws cards they have.
The original Cornucopia and Guilds were sold as separate sets, so we need to be able to select them separately.
The second edition however are sold as a single set, you can't have only 2nd Ed Guilds without 2nd Ed Cornucopia. So it makes more sense (to me at least) to have them as a single set "Cornucopia & Guilds".

Unless I mistaken about the 2nd Ed only being sold together?

**Comment by dbgalur** [comment]
You are not mistaken - there is only one second edition set.

As implemented, the user can only choose either Guilds 1E, Cornucopia 1E, or Cornucopia & Guilds 2E.

The difference is how the cards are displayed once they have been selected after a shuffle - as implemented, the new 2E cards will show up as Cornucopia or Guilds just like 1E counterparts (Option 2).  I'll update this code to have the 2E-only cards show up as 'Cornucopia & Guilds 2nd Edition' (Option 1). I'll let you know when I've made the modification (might be a few days).

**Comment by dbgalur** [comment]
Okay.  I've made the change.

Note that this matches the style of Dominion and Intrigue 2nd editions.  Seaside, Prosperity, and Hinterlands, however, identify the 2nd edition cards the same as the first edition cards. (The user can still choose which edition they want to include or limit, but when shuffled, the set that the cards show up in is the same).

**Comment by dbgalur** [comment]
Cornucopia & Guilds:
C and g

Intrigue and Dominion:
D and I

Prosperity (But the same goes for Seaside, and Hinterlands):
P

**Comment by TruthNZ** [comment]
> Okay. I've made the change.
> 
> Note that this matches the style of Dominion and Intrigue 2nd editions. Seaside, Prosperity, and Hinterlands, however, identify the 2nd edition cards the same as the first edition cards. (The user can still choose which edition they want to include or limit, but when shuffled, the set that the cards show up in is the same).
Yeah sadly. It's one of the limitations of the current design, and a reason I keep wanting to rebuild it ... I just don't have the time to even consider such a project.

**Pull request merged**
