### PR TITLE
Re-enable card language selection

### PR DESCRIPTION
**Pull request by UncleOwen**
Hi,

this pull-request re-enables card language selection.

Known issues:
- You need to restart the app after selecting a different language. (But this might have been the case in the original app?)
- Keeping all languages up-to-date will be a pain in the ass. If I remember correctly, Joran used a OpenOfficeCalc document and some ruby scripts to generate the JSON files. This made sure, that all languages hat the same cards (if translations were missing, the english name was used.) These files seem to be missing - and that's why the new cards for Adventures are completely missing from all non-english languages. Would you be open to a follow-up PR that removes a lot of redundancy from the translated JSON files, and stores just the translations in there? I would restore the old behaviour, that showed the english text if a translation was missing.

### CODE REVIEW

**Comment by TruthNZ** [comment]
Does the new version released handle what you want?

**Comment by UncleOwen** [comment]
Hi,

I don't see a new version in google play store.

**Comment by TruthNZ** [comment]
There's two different Dominion Shuffles.

The earlier version of this one was at:
https://play.google.com/store/apps/details?id=nl.spellenclubeindhoven.dominionshuffle
But for some reason doesn't seem to show up in the Play store (at least not
for me).
However when I try to upload my updated version of it, they say that it
still exists, and since has a different key (I don't have Jess's key to
sign the app with), I can't update the version there. I'm trying to work
with Google to sort something on this still.

The other Dominion Shuffle is:
https://play.google.com/store/apps/details?id=com.LukasMike.dominionshuffle
And is a completely different app.

The current latest release of our Dominion Shuffle is available at:
https://github.com/TruthNZ/DominionShuffle/releases (latest version is the
one with the green "Latest Release" tag next to it - annoyingly not always
at the top.
Until I can get it back up on the Play store you have to install this
manually.

In terms of languages, it picks up the native language from your
phone/tablet. If you want to display the card language at the moment you
have to change your phone/tablet language and restart the app.

Gynn Rickerby
Cell: 021 262 5205
There is no religion higher than the Truth.

**Comment by UncleOwen** [comment]
> In terms of languages, it picks up the native language from your phone/tablet.

That would mean I have to change my phone language everytime I use DominionShuffle - not good :(

**Comment by UncleOwen** [comment]
The "Umlauts" (special German language characters) are broken. I would have taken a look at it, but both the git repository and the source tarball marked 1.12.0 only contain the 1.10.0 source code :(

**Comment by TruthNZ** [comment]
Bah ...

Thanks, I'll get onto it.

Gynn Rickerby
Cell: 021 262 5205
There is no religion higher than the Truth.

**Comment by UncleOwen** [comment]
Btw, I really like the idea of defaulting the card language to the phone language... just add an override to the settings menu, please.

**Comment by TruthNZ** [comment]
Right, try this version:
https://github.com/TruthNZ/DominionShuffle/releases/tag/v1.12.1

I know the sorting isn't working in non-English languages correctly, that's
my next aim.

And looks like you can override the phone language for an App, without
having to have your own separate language system like Jess did - but it's a
little tricky. I'll see what I can do.

Gynn Rickerby
Cell: 021 262 5205
There is no religion higher than the Truth.

**Comment by UncleOwen** [comment]
Strange characters gone, umlauts working.

**Pull request closed without merging**
